FROM python:3

# Install curl
# Install unzip

RUN apt-get -yqq update && \
    apt-get -yqq install curl &&\
    apt-get -yqq install unzip &&\
    apt-get -yqq install gnupg

# Install required libs for chromedriver

RUN apt-get install -yqq libglib2.0-0 && \
    apt-get install -yqq libx11-6 && \
    apt-get install -yqq libnss3

# Set chromedriver version
ENV CHROMEDRIVER_VERSION 114.0.5735.90


# Install Chrome WebDriver
RUN mkdir -p /opt/chromedriver-${CHROMEDRIVER_VERSION} && \
    curl -sS -o /tmp/chromedriver_linux64.zip http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip && \
    unzip -qq /tmp/chromedriver_linux64.zip -d /opt/chromedriver-${CHROMEDRIVER_VERSION} && \
    rm /tmp/chromedriver_linux64.zip && \
    chmod +x /opt/chromedriver-${CHROMEDRIVER_VERSION}/chromedriver && \
    ln -fs /opt/chromedriver-${CHROMEDRIVER_VERSION}/chromedriver /usr/local/bin/chromedriver

# Install Google Chrome

#ENV CHROME_VERSION 114.0.5735.90 chrmoe no longer supports downloading older versions

RUN wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
  && apt install -y /tmp/chrome.deb \
  && rm /tmp/chrome.deb

EXPOSE 9515